version: '3'
services:
  auth:
    build:
      context: auth
      dockerfile: Dockerfile
    ports:
      - 4000:4000
  todo:
    build:
      context: todo
      dockerfile: setup/Dockerfile
    ports:
      - 4001:4001
